### ISSUE TITLE
Start recording hotkey doesnt work

### ISSUE THREAD

**Issue by Jarusz** [repeats/Repeat#29]
As the title says, i can only stop recording with the hotkey, but theres no way to start recoding with it?
Im using debian.

**Comment by hptruong93** [comment]
It should be the same hotkey as the stop recording action (default is F9). I'll take a closer look.

**Comment by hptruong93** [comment]
This is actually only a UI bug. Should be fixed with #4ca8ed83e6860d31999259abf462728e5cead0dd

**Comment by Jarusz** [comment]
It still doesnt work, sorry for late reply, i just downloaded the newest version, and recording hotkey still doesnt work
only the play/pause hotkey works

**Comment by hptruong93** [comment]
Did you force refresh (Ctrl + F5 on firefox, Shift + F5 on chrome) to make sure that the Javascript is update? Otherwise it may be using the cached old Javascript which didn't have the fix.

Another way to make sure there's no cache is to open it in a new incognito window.
